### ISSUE TITLE
cooja crush on ubuntu19.10

### ISSUE THREAD

**Issue by alexrayne** [contiki-ng/contiki-ng#1210]
Hallow! 
i try to simulate /examples/rpl-udp/rpl-udp-cooja.csc
used ubuntu19.10 (x64 AMD)
install tools according contiki-ng wiki (there is instaled JDK11)
building server and client alerts errors - obj can`t rename snprintf to log_snprintf error 139 with SEGFAULT. same for puts, printf.  this errors was ingoned
simulation starts well, and crushes fast. java crush dump have a mention that R11 contains libc.so.6: snprintf 

Can anybody help to solve it?

**Comment by alexrayne** [comment]
have setup and run docker image with contiki-ng
runing ant well
run  /examples/rpl-udp/rpl-udp-cooja.csc starts build server mote with same errors:


```
> make udp-server.cooja TARGET=cooja 
fatal: Not a git repository: '../../.git'
  CC        udp-server.c --> udp-server.o
  CC        ../../arch/platform/cooja/./platform.c --> platform.o
mv platform.o build/cooja/mtype129.o
ar rcf build/cooja/mtype129.a build/cooja/obj/simEnvChange.o build/cooja/obj/cooja_mt.o .... /obj/rpl-dag-root.o 
Redefining printf
objcopy --redefine-sym printf=log_printf udp-server.o;   objcopy --redefine-sym printf=log_printf build/cooja/mtype129.o;   objcopy --redefine-sym printf=log_printf build/cooja/mtype129.a; 
Segmentation fault (core dumped)
make: [build/cooja/mtype129.cooja] Error 139 (ignored)
../../arch/platform/cooja/Makefile.customrules-cooja:21: recipe for target 'build/cooja/mtype129.cooja' failed
objcopy --redefine-sym puts=log_puts udp-server.o;   objcopy --redefine-sym puts=log_puts build/cooja/mtype129.o;   objcopy --redefine-sym puts=log_puts build/cooja/mtype129.a; 
Segmentation fault (core dumped)
make: [build/cooja/mtype129.cooja] Error 139 (ignored)
../../arch/platform/cooja/Makefile.customrules-cooja:21: recipe for target 'build/cooja/mtype129.cooja' failed
objcopy --redefine-sym putchar=log_putchar udp-server.o;   objcopy --redefine-sym putchar=log_putchar build/cooja/mtype129.o;   objcopy --redefine-sym putchar=log_putchar build/cooja/mtype129.a; 
Segmentation fault (core dumped)
../../arch/platform/cooja/Makefile.customrules-cooja:21: recipe for target 'build/cooja/mtype129.cooja' failed
gcc -I'/usr/lib/jvm/default-java/include' -I'/usr/lib/jvm/default-java/include/linux' -shared -Wl,-Map=build/cooja/mtype129.map -o build/cooja/mtype129.cooja udp-server.o build/cooja/mtype129.o build/cooja/mtype129.a 
make: [build/cooja/mtype129.cooja] Error 139 (ignored)
cp build/cooja/mtype129.cooja udp-server.cooja
rm udp-server.o

```

after that build, place mote to simulation fails with:

```
org.contikios.cooja.Cooja$SimulationCreationException: Mote type creation error: Error when creating corecomm instance: Lib1
	at org.contikios.cooja.Cooja.loadSimulationConfig(Cooja.java:3453)
	at org.contikios.cooja.Cooja.loadSimulationConfig(Cooja.java:3363)
	at org.contikios.cooja.Cooja.doLoadConfig(Cooja.java:2410)
	at org.contikios.cooja.Cooja$4.run(Cooja.java:625)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.contikios.cooja.MoteType$MoteTypeCreationException: Error when creating corecomm instance: Lib1
	at org.contikios.cooja.CoreComm.createCoreComm(CoreComm.java:326)
	at org.contikios.cooja.contikimote.ContikiMoteType.doInit(ContikiMoteType.java:407)
	at org.contikios.cooja.contikimote.ContikiMoteType.configureAndInit(ContikiMoteType.java:368)
	at org.contikios.cooja.contikimote.ContikiMoteType.setConfigXML(ContikiMoteType.java:1341)
	at org.contikios.cooja.Simulation.setConfigXML(Simulation.java:703)
	at org.contikios.cooja.Cooja.loadSimulationConfig(Cooja.java:3434)
	... 4 more
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.contikios.cooja.CoreComm.createCoreComm(CoreComm.java:318)
	... 9 more
Caused by: java.lang.UnsatisfiedLinkError: /home/user/contiki-ng/examples/rpl-udp/build/cooja/mtype38.cooja: /home/user/contiki-ng/examples/rpl-udp/build/cooja/mtype38.cooja: undefined symbol: log_printf
	at java.lang.ClassLoader$NativeLibrary.load(Native Method)
	at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1941)
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1824)
	at java.lang.Runtime.load0(Runtime.java:809)
	at java.lang.System.load(System.java:1086)
	at org.contikios.cooja.corecomm.Lib1.<init>(Lib1.java:49)
	... 14 more

```

**Comment by alexrayne** [comment]
Crush of simulation create in docker i have fixed, and it is run well.
But simulation in native JVM11 shurely crash in external code:

```
Stack: [0x00007fe3243b6000,0x00007fe3244b7000],  sp=0x00007fe32409f048,  free space=18014398509478820k
Native frames: (J=compiled Java code, A=aot compiled Java code, j=interpreted, Vv=VM code, C=native code)
C  [libc.so.6+0x96f3d]

Java frames: (J=compiled Java code, j=interpreted, Vv=VM code)
j  org.contikios.cooja.corecomm.Lib2.tick()V+0
j  org.contikios.cooja.contikimote.ContikiMoteType.tick()V+4
j  org.contikios.cooja.contikimote.ContikiMote.execute(J)V+63
j  org.contikios.cooja.motes.AbstractWakeupMote$1.execute(J)V+5
j  org.contikios.cooja.Simulation.run()V+148
j  java.lang.Thread.run()V+11 java.base@11.0.6
v  ~StubRoutines::call_stub

siginfo: si_signo: 11 (SIGSEGV), si_code: 128 (SI_KERNEL), si_addr: 0x0000000000000000

Register to memory mapping:

RAX=0x00007fe37e9511a0: <offset 0x00000000001ec1a0> in /lib/x86_64-linux-gnu/libc.so.6 at 0x00007fe37e765000
RBX=0x00007fe3240a13bf: <offset 0x00000000000383bf> in /media/sf_projects/contiking.hggit/examples/rpl-udp/build/cooja/mtype376.cooja at 0x00007fe324069000
RCX=0x0 is NULL
RDX=0x00007fe3240a13bf: <offset 0x00000000000383bf> in /media/sf_projects/contiking.hggit/examples/rpl-udp/build/cooja/mtype376.cooja at 0x00007fe324069000
RSP=0x00007fe32409f048: <offset 0x0000000000036048> in /media/sf_projects/contiking.hggit/examples/rpl-udp/build/cooja/mtype376.cooja at 0x00007fe324069000
RBP=0x00007fe32409f098: <offset 0x0000000000036098> in /media/sf_projects/contiking.hggit/examples/rpl-udp/build/cooja/mtype376.cooja at 0x00007fe324069000
RSI=0x00007fe32409f3c0: <offset 0x00000000000363c0> in /media/sf_projects/contiking.hggit/examples/rpl-udp/build/cooja/mtype376.cooja at 0x00007fe324069000
RDI=0x00007fe32409f098: <offset 0x0000000000036098> in /media/sf_projects/contiking.hggit/examples/rpl-udp/build/cooja/mtype376.cooja at 0x00007fe324069000
R8 =0x0 is NULL
R9 =0x00007fe32409f188: <offset 0x0000000000036188> in /media/sf_projects/contiking.hggit/examples/rpl-udp/build/cooja/mtype376.cooja at 0x00007fe324069000
R10=0x00007fe32406ec3d: <offset 0x0000000000005c3d> in /media/sf_projects/contiking.hggit/examples/rpl-udp/build/cooja/mtype376.cooja at 0x00007fe324069000
R11=0x00007fe37e7f4090: vsnprintf+0x0000000000000000 in /lib/x86_64-linux-gnu/libc.so.6 at 0x00007fe37e765000
R12=0x00007fe32409f3c0: <offset 0x00000000000363c0> in /media/sf_projects/contiking.hggit/examples/rpl-udp/build/cooja/mtype376.cooja at 0x00007fe324069000
R13=0x00007fe32409f3c0: <offset 0x00000000000363c0> in /media/sf_projects/contiking.hggit/examples/rpl-udp/build/cooja/mtype376.cooja at 0x00007fe324069000
R14=0x00007fe324091152: <offset 0x0000000000028152> in /media/sf_projects/contiking.hggit/examples/rpl-udp/build/cooja/mtype376.cooja at 0x00007fe324069000
R15=0x00007fe32409f238: <offset 0x0000000000036238> in /media/sf_projects/contiking.hggit/examples/rpl-udp/build/cooja/mtype376.cooja at 0x00007fe324069000

```

**Comment by alexrayne** [comment]
it looks related #678 and #134
