### ISSUE TITLE
Cooja gui not working inside Docker container

### ISSUE THREAD

**Issue by Telespielstube** [contiki-ng/contiki-ng#1426]
Seems I still cannot get Cooja GUI it to run on my Mac. Im on the latest version 10.15.7 (19H2)

My setup looks like this:

`./bashrc:`

`export CNG_PATH=/Users/marta/contiki-ng`

`alias contiker="docker run \`
`--privileged \`
`--sysctl net.ipv6.conf.all.disable_ipv6=0 \`
`--mount type=bind,source=$CNG_PATH,destination=/home/user/contiki-ng \`
`-e DISPLAY=docker.for.mac.host.internal:0 \`
`-ti contiker/contiki-ng"`

I open xQuartz and map the tcp port 6000

`$ open -a XQuartz $ socat TCP-LISTEN:6000,reuseaddr,fork UNIX-CLIENT:\"$DISPLAY\"`

I check the connection in a second terminal:
`$ lsof -i TCP:6000`

COMMAND PID USER FD TYPE DEVICE SIZE/OFF NODE NAME
X11.bin 10178 marta 12u IPv6 0xb2295e400fec2efd 0t0 TCP *:6000 (LISTEN)
socat 11304 marta 5u IPv4 0xb2295e401ef72a4d 0t0 TCP *:6000 (LISTEN)

I run Cooja from the container:

`$ contiker cooja`

and this is the output from the docker container:

`run:`
`[java] Exception in thread "main" java.awt.AWTError: Can't connect to X11 window server using docker.for.mac.host.internal:0' as the value of the DISPLAY variable.`
`[java] at sun.awt.X11GraphicsEnvironment.initDisplay(Native Method)`
`[java] at sun.awt.X11GraphicsEnvironment.access$200(X11GraphicsEnvironment.java:65)`
`[java] at sun.awt.X11GraphicsEnvironment$1.run(X11GraphicsEnvironment.java:115)`
`[java] at java.security.AccessController.doPrivileged(Native Method)`
`[java] at sun.awt.X11GraphicsEnvironment.<clinit>(X11GraphicsEnvironment.java:74)`
`[java] at java.lang.Class.forName0(Native Method)`
`[java] at java.lang.Class.forName(Class.java:264)`
`[java] at java.awt.GraphicsEnvironment.createGE(GraphicsEnvironment.java:103)`
`[java] at java.awt.GraphicsEnvironment.getLocalGraphicsEnvironment(GraphicsEnvironment.java:82)`
`[java] at sun.awt.X11.XToolkit.<clinit>(XToolkit.java:132)`
`[java] at java.lang.Class.forName0(Native Method)`
`[java] at java.lang.Class.forName(Class.java:264)`
`[java] at java.awt.Toolkit$2.run(Toolkit.java:860)`
`[java] at java.awt.Toolkit$2.run(Toolkit.java:855)`
`[java] at java.security.AccessController.doPrivileged(Native Method)`
`[java] at java.awt.Toolkit.getDefaultToolkit(Toolkit.java:854)`
`[java] at sun.swing.SwingUtilities2.getSystemMnemonicKeyMask(SwingUtilities2.java:2032)`
`[java] at javax.swing.plaf.basic.BasicLookAndFeel.initComponentDefaults(BasicLookAndFeel.java:1158)`
`[java] at javax.swing.plaf.metal.MetalLookAndFeel.initComponentDefaults(MetalLookAndFeel.java:431)`
`[java] at javax.swing.plaf.basic.BasicLookAndFeel.getDefaults(BasicLookAndFeel.java:148)`
`[java] at javax.swing.plaf.metal.MetalLookAndFeel.getDefaults(MetalLookAndFeel.java:1577)`
`[java] at javax.swing.UIManager.setLookAndFeel(UIManager.java:539)`
`[java] at javax.swing.UIManager.setLookAndFeel(UIManager.java:579)`
`[java] at javax.swing.UIManager.initializeDefaultLAF(UIManager.java:1349)`
`[java] at javax.swing.UIManager.initialize(UIManager.java:1459)`
`[java] at javax.swing.UIManager.maybeInitialize(UIManager.java:1426)`
`[java] at javax.swing.UIManager.getInstalledLookAndFeels(UIManager.java:419)`
`[java] at org.contikios.cooja.Cooja.setLookAndFeel(Cooja.java:1239)`
`[java] at org.contikios.cooja.Cooja.main(Cooja.java:3168)`
`[java] Java Result: 1`

If I check socat I get the following error:

`2020/10/24 16:53:19 socat[11326] E connect(5, LEN=68 AF=1` `"/private/tmp/com.apple.launchd.dJsE2ZqFeo/org.macosforge.xquartz:0", 68): Connection refused`

**Comment by Telespielstube** [comment]
Changed the `.bashrc` from 

`-e DISPLAY=docker.for.mac.host.internal:0 \`
to

`-e DISPLAY=host.docker.internal:0`

now it works.
