### ISSUE TITLE
MAC OS cooja issue

### ISSUE THREAD

**Issue by elisabethEmack** [contiki-ng/contiki-ng#1765]
I have the following issue while trying to run cooja in my MAC. I have done several instalation attempts but no meaningful progress. If anyone knows, I am in need of your help, been dealing the problem for 2 weeks now. Many thanks!

i am running on M1-Apple ...could get cooja running natively
but not thru docker..
i followed the same as above by @Telespielstube ...what i get is:

Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.ExceptionInInitializerError
	at java.util.Locale.getDefault(Locale.java:836)
	at java.text.MessageFormat.<init>(MessageFormat.java:361)
	at java.text.MessageFormat.format(MessageFormat.java:840)
	at sun.launcher.LauncherHelper.getLocalizedMessage(LauncherHelper.java:426)
	at sun.launcher.LauncherHelper.abort(LauncherHelper.java:547)
	at sun.launcher.LauncherHelper.validateMainClass(LauncherHelper.java:653)
	at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:632)
Caused by: java.lang.ArrayIndexOutOfBoundsException: 0
	at java.util.Locale$1.<clinit>(Locale.java:836)
	... 7 more

_Originally posted by @vinobc in https://github.com/contiki-ng/contiki-ng/issues/1426#issuecomment-944241775_

**Comment by pjonsson** [comment]
This is a duplicate of #1670.
