### ISSUE TITLE
Cooja remembers Append to file from previous run

### ISSUE THREAD

**Issue by rahav** [contiki-ng/contiki-ng#2649]
### Discussed in https://github.com/contiki-ng/contiki-ng/discussions/2647

<div type='discussions-op-text'>

<sup>Originally posted by **rahav** August 30, 2023</sup>
Scenario: Run Cooja and select a simulation file. In the Mote output window, File --> Append to file. Specify a file name. Run the simulation. Uncheck the Append to file and exit Cooja to the container prompt.

Run Cooja and select a simulation file. Even though it was unchecked, Cooja still remembers the Append to file (see attached). If you run the simulation, it will fail with the following message.

````
ERROR [sim] [LogListener.java:833] - Append file failed: /home/user/contiki-ng/Rahav/idempotentM/tests/unziped/rel0.17/paper_runs/c0.01_d0.04/sim2_INFO.txt
java.nio.file.NoSuchFileException: /home/user/contiki-ng/Rahav/idempotentM/tests/unziped/rel0.17/paper_runs/c0.01_d0.04/sim2_INFO.txt
        at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:92)
        at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:106)
        at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
        at java.base/sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:218)
        at java.base/java.nio.file.spi.FileSystemProvider.newOutputStream(FileSystemProvider.java:484)
        at java.base/java.nio.file.Files.newOutputStream(Files.java:228)
        at java.base/java.nio.file.Files.newBufferedWriter(Files.java:3008)
        at org.contikios.cooja.plugins.LogListener.appendToFile(LogListener.java:829)
        at org.contikios.cooja.plugins.LogListener.lambda$new$5(LogListener.java:581)
        at org.contikios.cooja.SimEventCentral.lambda$new$1(SimEventCentral.java:83)
        at org.contikios.cooja.util.EventTriggers.trigger(EventTriggers.java:111)
        at org.contikios.cooja.dialogs.SerialUI.dataReceived(SerialUI.java:105)
        at org.contikios.cooja.contikimote.interfaces.ContikiRS232.doActionsAfterTick(ContikiRS232.java:96)
        at org.contikios.cooja.contikimote.ContikiMote.execute(ContikiMote.java:131)
        at org.contikios.cooja.motes.AbstractWakeupMote$1.execute(AbstractWakeupMote.java:67)
        at org.contikios.cooja.Simulation.lambda$new$0(Simulation.java:226)
        at java.base/java.lang.Thread.run(Thread.java:833)
````
<img width="169" alt="Screen Shot 2023-08-30 at 15 46 08" src="https://github.com/contiki-ng/contiki-ng/assets/2912950/934d18a1-ce57-4d82-87bc-5e815d9452aa">

</div>

**Comment by rahav** [comment]
When the time comes to help trace the bug, I notice that Cooja will display the following message when it invokes.

[java] WARN [Thread-0] (Cooja.java:4313) - Replaced [CONTIKI_DIR]/Rahav/idempotentM/tests/unziped/rel0.17/paper_runs/c0.01_d0.04/sim2_INFO.txt with /home/user/contiki-ng/Rahav/idempotentM/tests/unziped/rel0.17/paper_runs/c0.01_d0.04/sim2_INFO.txt (default: /home/user/contiki-ng/tools/cooja/), but could not find it. This does not have to be an error, as the file might be created later.
