### ISSUE TITLE
Failed to upload firmware to nrf52840 dongle

### ISSUE THREAD

**Issue by marek22k** [contiki-ng/contiki-ng#2837]
Hello,

after I managed to compile the firmware, I can't upload it:

```
$ make TARGET=nrf52840 BOARD=dongle node.dfu-upload PORT=/dev/ttyACM0
which: no nrfjprog in (/home/marek/gcc-arm-none-eabi-10.3-2021.10/bin:/home/marek/.rvm/gems/ruby-3.2.2/bin:/home/marek/.rvm/gems/ruby-3.2.2@global/bin:/home/marek/.rvm/rubies/ruby-3.2.2/bin:/home/marek/perl5/bin:/home/marek/.local/bin:/home/marek/.nvm/versions/node/v20.10.0/bin:/home/marek/.pyenv/shims:/home/marek/.pyenv/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/var/lib/flatpak/exports/bin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:/usr/lib/rustup/bin:/home/marek/.rvm/bin:/home/marek/.rvm/bin:/home/marek/go/bin)
which: no nrfjprog in (/home/marek/gcc-arm-none-eabi-10.3-2021.10/bin:/home/marek/.rvm/gems/ruby-3.2.2/bin:/home/marek/.rvm/gems/ruby-3.2.2@global/bin:/home/marek/.rvm/rubies/ruby-3.2.2/bin:/home/marek/perl5/bin:/home/marek/.local/bin:/home/marek/.nvm/versions/node/v20.10.0/bin:/home/marek/.pyenv/shims:/home/marek/.pyenv/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/var/lib/flatpak/exports/bin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:/usr/lib/rustup/bin:/home/marek/.rvm/bin:/home/marek/.rvm/bin:/home/marek/go/bin)
which: no rlwrap in (/home/marek/gcc-arm-none-eabi-10.3-2021.10/bin:/home/marek/.rvm/gems/ruby-3.2.2/bin:/home/marek/.rvm/gems/ruby-3.2.2@global/bin:/home/marek/.rvm/rubies/ruby-3.2.2/bin:/home/marek/perl5/bin:/home/marek/.local/bin:/home/marek/.nvm/versions/node/v20.10.0/bin:/home/marek/.pyenv/shims:/home/marek/.pyenv/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/var/lib/flatpak/exports/bin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:/usr/lib/rustup/bin:/home/marek/.rvm/bin:/home/marek/.rvm/bin:/home/marek/go/bin)
nrfutil pkg generate --hw-version 52 --sd-req 0x00 --debug-mode --application build/nrf52840/dongle/node.hex build/nrf52840/dongle/nrf52840_dfu_image.zip

|===============================================================|
|##      ##    ###    ########  ##    ## #### ##    ##  ######  |
|##  ##  ##   ## ##   ##     ## ###   ##  ##  ###   ## ##    ## |
|##  ##  ##  ##   ##  ##     ## ####  ##  ##  ####  ## ##       |
|##  ##  ## ##     ## ########  ## ## ##  ##  ## ## ## ##   ####|
|##  ##  ## ######### ##   ##   ##  ####  ##  ##  #### ##    ## |
|##  ##  ## ##     ## ##    ##  ##   ###  ##  ##   ### ##    ## |
| ###  ###  ##     ## ##     ## ##    ## #### ##    ##  ######  |
|===============================================================|
|You are generating a package with the debug bit enabled in the |
|init packet. This is only compatible with a debug bootloader   |
|and is not suitable for production.                            |
|===============================================================|


|===============================================================|
|##      ##    ###    ########  ##    ## #### ##    ##  ######  |
|##  ##  ##   ## ##   ##     ## ###   ##  ##  ###   ## ##    ## |
|##  ##  ##  ##   ##  ##     ## ####  ##  ##  ####  ## ##       |
|##  ##  ## ##     ## ########  ## ## ##  ##  ## ## ## ##   ####|
|##  ##  ## ######### ##   ##   ##  ####  ##  ##  #### ##    ## |
|##  ##  ## ##     ## ##    ##  ##   ###  ##  ##   ### ##    ## |
| ###  ###  ##     ## ##     ## ##    ## #### ##    ##  ######  |
|===============================================================|
|You are not providing a signature key, which means the DFU     |
|files will not be signed, and are vulnerable to tampering.     |
|This is only compatible with a signature-less bootloader and is|
|not suitable for production environments.                      |
|===============================================================|

Traceback (most recent call last):
  File "/home/marek/.pyenv/versions/3.12.0/bin/nrfutil", line 8, in <module>
    sys.exit(cli())
             ^^^^^
  File "/home/marek/.pyenv/versions/3.12.0/lib/python3.12/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/marek/.pyenv/versions/3.12.0/lib/python3.12/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/home/marek/.pyenv/versions/3.12.0/lib/python3.12/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/marek/.pyenv/versions/3.12.0/lib/python3.12/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/marek/.pyenv/versions/3.12.0/lib/python3.12/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/marek/.pyenv/versions/3.12.0/lib/python3.12/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/marek/.pyenv/versions/3.12.0/lib/python3.12/site-packages/nordicsemi/__main__.py", line 867, in generate
    package.generate_package(zipfile_path)
  File "/home/marek/.pyenv/versions/3.12.0/lib/python3.12/site-packages/nordicsemi/dfu/package.py", line 403, in generate_package
    for key, firmware_data in self.firmwares_data.iteritems():
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'dict' object has no attribute 'iteritems'
make: *** [../../arch/cpu/nrf52840/Makefile.nrf52840:180: node.dfu-upload] Error 1
$ pip3 show nrfutil
Name: nrfutil
Version: 5.2.0
Summary: Nordic Semiconductor nrfutil utility and Python library
Home-page: https://github.com/NordicSemiconductor/pc-nrfutil
Author: Nordic Semiconductor ASA
Author-email: 
License: Modified BSD License
Location: /home/marek/.pyenv/versions/3.12.0/lib/python3.12/site-packages
Requires: behave, click, crcmod, ecdsa, enum34, intelhex, libusb1, pc-ble-driver-py, piccata, protobuf, pyserial, pyspinel, pyyaml, six, tqdm
Required-by: 
```

**Comment by pjonsson** [comment]
That looks like #2657.
